name: Test and Deploy Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: '7.x'
  BUILD_CONFIGURATION: 'Release'
  BUILD_OUTPUT_PATH: '**/bin/Release/net8.0/**'
  NUGET_CACHE_PATH: ~/.nuget/packages

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache .NET dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_CACHE_PATH }}
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Run tests
        run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --verbosity normal

      - name: Save Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}
          include-hidden-files: true
          if-no-files-found: warn

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy Project
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          echo "Deploying project using the token..."
          echo "Token: $DEPLOYMENT_TOKEN" # For demonstration only; avoid printing secrets in real workflows.

  report: 
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
        if: failure()
      - name: output information
        run: |
          echo "Something went wrong"
          echo ${{toJSON(github)}}
        if: success()
      - name: success information
        run: |
          echo "everything is ok"
    

